module Constants
  # Generated using PatternGenerator::create_patterns(64)
  PATTERNS = Set[
    "WWWWWWBB", "WWWBBBWW", "BBBWBBBB", "WBWWWWWB", "WBWBBWWW", "BWWBBBBB", "BWWWBBBB", "WBBWBWWB",
    "BBWWWBWB", "WWBWWWBW", "WBBWBBBW", "WWWBBWWB", "BWWBWWBB", "BBBWBBBW", "WBBWWBWB", "WWWWWBBW",
    "BWBWWBWW", "WBWBWBWW", "BBBWBWBW", "WWWBBBWB", "BBWBBBBB", "BBBWWBWB", "WWBBWWBW", "BBBBWWWW",
    "BWBWWBBB", "WWBWBBWW", "WBWBWBBB", "BWBBBBWW", "BBBWBBWB", "WWBBWBWB", "BBWBWWBW", "BWWWBBBW",
    "BBBBWBBW", "BWBWWWBW", "WBBWBBWW", "WWBWWBWB", "WWBWWBBW", "WWBWWWWW", "WBBBWBBW", "BWWWWBBW",
    "BBBWWWWW", "WBWWBBWW", "WWBWWWWB", "WWBWBWWW", "WBBBWBBB", "BWWBWWWW", "BWBBWWBW", "BBBWWWBW",
    "WWWBBBBB", "BWBWBBWB", "WWWWWWWB", "WWWBBBBW", "BBBBWBWB", "BWWBBBWW", "BBWBWWBB", "BBWBBWWW",
    "WBBWBBWB", "WWBBWBBB", "BWWBBWBW", "BBBBWWBB", "BWBBBBBW", "BWBBWWBB", "BBWBWWWW", "BWWBBWWB"
  ].freeze
end